/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    instructions: Instruction;
    'shared-steps': SharedStep;
    'shared-step-groups': SharedStepGroup;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    instructions: InstructionsSelect<false> | InstructionsSelect<true>;
    'shared-steps': SharedStepsSelect<false> | SharedStepsSelect<true>;
    'shared-step-groups': SharedStepGroupsSelect<false> | SharedStepGroupsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('cs' | 'da' | 'de' | 'en' | 'es' | 'fr' | 'hu' | 'it' | 'ko' | 'nl' | 'no' | 'pl' | 'pt' | 'sk' | 'sv' | 'zh')
    | ('cs' | 'da' | 'de' | 'en' | 'es' | 'fr' | 'hu' | 'it' | 'ko' | 'nl' | 'no' | 'pl' | 'pt' | 'sk' | 'sv' | 'zh')[];
  globals: {};
  globalsSelect: {};
  locale: 'cs' | 'da' | 'de' | 'en' | 'es' | 'fr' | 'hu' | 'it' | 'ko' | 'nl' | 'no' | 'pl' | 'pt' | 'sk' | 'sv' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructions".
 */
export interface Instruction {
  id: number;
  phoneModel: string;
  instructionType: 'activate' | 'connect';
  activate?: {
    /**
     * Optional short/base instructions for the activate screen.
     */
    base?:
      | {
          source: 'inline' | 'sharedStep' | 'sharedStepGroup';
          inline?: {
            /**
             * Optional step title/name.
             */
            name?: string | null;
            description: string;
            /**
             * Optional image, GIF, or video.
             */
            media?: (number | null) | Media;
          };
          sharedStep?: (number | null) | SharedStep;
          sharedStepGroup?: (number | null) | SharedStepGroup;
          id?: string | null;
        }[]
      | null;
    /**
     * Detailed instructions shown when the user opens detailed instructions.
     */
    detailed: {
      source: 'inline' | 'sharedStep' | 'sharedStepGroup';
      inline?: {
        /**
         * Optional step title/name.
         */
        name?: string | null;
        description: string;
        /**
         * Optional image, GIF, or video.
         */
        media?: (number | null) | Media;
      };
      sharedStep?: (number | null) | SharedStep;
      sharedStepGroup?: (number | null) | SharedStepGroup;
      id?: string | null;
    }[];
  };
  connect?: {
    /**
     * Add one item for each connect substep.
     */
    subSteps: {
      /**
       * Select which connect substep these instructions belong to.
       */
      key: 'rename' | 'turn_on' | 'roaming';
      /**
       * Short instructions shown directly on this substep screen.
       */
      base?:
        | {
            source: 'inline' | 'sharedStep' | 'sharedStepGroup';
            inline?: {
              /**
               * Optional step title/name.
               */
              name?: string | null;
              description: string;
              /**
               * Optional image, GIF, or video.
               */
              media?: (number | null) | Media;
            };
            sharedStep?: (number | null) | SharedStep;
            sharedStepGroup?: (number | null) | SharedStepGroup;
            id?: string | null;
          }[]
        | null;
      /**
       * Detailed instructions for this substep. Use shared steps/groups if this content is reused.
       */
      detailed: {
        source: 'inline' | 'sharedStep' | 'sharedStepGroup';
        inline?: {
          /**
           * Optional step title/name.
           */
          name?: string | null;
          description: string;
          /**
           * Optional image, GIF, or video.
           */
          media?: (number | null) | Media;
        };
        sharedStep?: (number | null) | SharedStep;
        sharedStepGroup?: (number | null) | SharedStepGroup;
        id?: string | null;
      }[];
      id?: string | null;
    }[];
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shared-steps".
 */
export interface SharedStep {
  id: number;
  /**
   * Internal name used only in Payload to identify this reusable step.
   */
  internalName: string;
  usageType: 'base' | 'detailed' | 'both';
  /**
   * Optional visible step title/name.
   */
  name?: string | null;
  description: string;
  /**
   * Optional image, GIF, or video.
   */
  media?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shared-step-groups".
 */
export interface SharedStepGroup {
  id: number;
  /**
   * Internal name used only in Payload to identify this reusable step group.
   */
  internalName: string;
  /**
   * Optional description for editors.
   */
  description?: string | null;
  steps: {
    step: number | SharedStep;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'instructions';
        value: number | Instruction;
      } | null)
    | ({
        relationTo: 'shared-steps';
        value: number | SharedStep;
      } | null)
    | ({
        relationTo: 'shared-step-groups';
        value: number | SharedStepGroup;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructions_select".
 */
export interface InstructionsSelect<T extends boolean = true> {
  phoneModel?: T;
  instructionType?: T;
  activate?:
    | T
    | {
        base?:
          | T
          | {
              source?: T;
              inline?:
                | T
                | {
                    name?: T;
                    description?: T;
                    media?: T;
                  };
              sharedStep?: T;
              sharedStepGroup?: T;
              id?: T;
            };
        detailed?:
          | T
          | {
              source?: T;
              inline?:
                | T
                | {
                    name?: T;
                    description?: T;
                    media?: T;
                  };
              sharedStep?: T;
              sharedStepGroup?: T;
              id?: T;
            };
      };
  connect?:
    | T
    | {
        subSteps?:
          | T
          | {
              key?: T;
              base?:
                | T
                | {
                    source?: T;
                    inline?:
                      | T
                      | {
                          name?: T;
                          description?: T;
                          media?: T;
                        };
                    sharedStep?: T;
                    sharedStepGroup?: T;
                    id?: T;
                  };
              detailed?:
                | T
                | {
                    source?: T;
                    inline?:
                      | T
                      | {
                          name?: T;
                          description?: T;
                          media?: T;
                        };
                    sharedStep?: T;
                    sharedStepGroup?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shared-steps_select".
 */
export interface SharedStepsSelect<T extends boolean = true> {
  internalName?: T;
  usageType?: T;
  name?: T;
  description?: T;
  media?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shared-step-groups_select".
 */
export interface SharedStepGroupsSelect<T extends boolean = true> {
  internalName?: T;
  description?: T;
  steps?:
    | T
    | {
        step?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}